In [3]:
import numpy as np
from numpy import random
import pandas as pd

In [10]:
data = pd.read_csv('./data/Boston.csv')
print(data.shape)
print(f'No of training set: {data.shape[0]}')
print(f'No of features set: {data.shape[1]}')
print(type(data))
data.head()

(506, 15)
No of training set: 506
No of features set: 15
<class 'pandas.core.frame.DataFrame'>


Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [17]:
data = np.array(data)
input = data[0:506, 1:14]
output = data[0:506, 14:15]

print(input.shape)
print(input)

print(output.shape)
print(output)

(506, 13)
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(506, 1)
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]
 [15. ]
 [18.9]
 [21.7]
 [20.4]
 [18.2]
 [19.9]
 [23.1]
 [17.5]
 [20.2]
 [18.2]
 [13.6]
 [19.6]
 [15.2]
 [14.5]
 [15.6]
 [13.9]
 [16.6]
 [14.8]
 [18.4]
 [21. ]
 [12.7]
 [14.5]
 [13.2]
 [13.1]
 [13.5]
 [18.9]
 [20. ]
 [21. ]
 [24.7]
 [30.8]
 [34.9]
 [26.6]
 [25.3]
 [24.7]
 [21.2]
 [19.3]
 [20. ]
 [16.6]
 [14.4]
 [19.4]
 [19.7]
 [20.5]
 [25. ]
 [23.4]
 [18.9]
 [35.4]
 [24.7]
 [31.6]
 [23.3]
 [19.6]
 [18.7]
 [16. ]
 [22.2]
 [25. ]
 [33. ]
 [23.5]
 [19.4]
 

In [18]:
theta = random.randn(input.shape[1], 1)
print(theta)
print(theta.shape)

[[-0.05602784]
 [-1.38436855]
 [-2.25677865]
 [ 0.41692005]
 [ 0.37638456]
 [-0.80174973]
 [ 0.44963069]
 [-0.29985004]
 [-0.28702616]
 [-1.30613144]
 [-0.68068992]
 [ 0.08240205]
 [ 0.43422852]]
(13, 1)


In [20]:
# normal equation = (XT . X)^-1 . XT . Y
def loss_function(input, output, theta):
  temp = (np.dot(input, theta) - output)
  loss = np.dot(np.transpose(temp), temp) / input.shape[0]
  return loss[0][0]

print(loss_function(input, output, theta))

352471.7640125499


In [ ]:
def normal_equation(input, output):
  a = np.linalg.inv(np.dot(np.transpose(input), input))
  b = np.dot(np.transpose(input), output)
  return np.dot(a, b)

new_theta = normal_equation(input, output)
new_loss = loss_function(input, output, new_theta)
print(new_loss)

24.166099330126485
